"""create_initial_tables

Revision ID: 24439b3156c7
Revises:
Create Date: 2025-06-03 15:02:44.309690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24439b3156c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_senders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_address', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('spam_strike_count', sa.Integer(), nullable=False),
    sa.Column('first_strike_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_strike_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_permanently_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_address')
    )
    op.create_index('idx_blocked_senders_sender_address', 'blocked_senders', ['sender_address'], unique=True)
    op.create_index(op.f('ix_blocked_senders_id'), 'blocked_senders', ['id'], unique=False)
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), nullable=False),
    sa.Column('imap_host', sa.VARCHAR(), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_login', sa.VARCHAR(), nullable=False),
    sa.Column('imap_password_encrypted', sa.VARCHAR(), nullable=False),
    sa.Column('monitored_folders', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_uid_map', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index('idx_mailboxes_email_address', 'mailboxes', ['email_address'], unique=True)
    op.create_index(op.f('ix_mailboxes_id'), 'mailboxes', ['id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('message_uid', sa.VARCHAR(), nullable=False),
    sa.Column('folder_name', sa.VARCHAR(), nullable=False),
    sa.Column('message_id_header', sa.VARCHAR(), nullable=True),
    sa.Column('sender_address', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_address', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('body_text', sa.TEXT(), nullable=True),
    sa.Column('received_at_header', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), nullable=False),
    sa.Column('apt_from_recipient_address', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_details', sa.TEXT(), nullable=True),
    sa.Column('hash_body_text', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emails_hash_body_text', 'emails', ['hash_body_text'], unique=False)
    op.create_index('idx_emails_mailbox_folder_uid', 'emails', ['mailbox_id', 'folder_name', 'message_uid'], unique=True)
    op.create_index('idx_emails_processing_status', 'emails', ['processing_status'], unique=False)
    op.create_index('idx_emails_received_at_header', 'emails', ['received_at_header'], unique=False)
    op.create_index('idx_emails_sender_address', 'emails', ['sender_address'], unique=False)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index('idx_emails_sender_address', table_name='emails')
    op.drop_index('idx_emails_received_at_header', table_name='emails')
    op.drop_index('idx_emails_processing_status', table_name='emails')
    op.drop_index('idx_emails_mailbox_folder_uid', table_name='emails')
    op.drop_index('idx_emails_hash_body_text', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_mailboxes_id'), table_name='mailboxes')
    op.drop_index('idx_mailboxes_email_address', table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_blocked_senders_id'), table_name='blocked_senders')
    op.drop_index('idx_blocked_senders_sender_address', table_name='blocked_senders')
    op.drop_table('blocked_senders')
    # ### end Alembic commands ###
